### ISSUE TITLE
Traffic Ops Golang Panics if Error or Event Loggers are nil

### ISSUE THREAD

**Issue by rob05c** [apache/incubator-trafficcontrol#1589]
Traffic Ops should allow users to set any logger to nil, including the Error and Event loggers. Currently, it panics if either is nil. 

The problem is here: https://github.com/apache/incubator-trafficcontrol/blob/80c767f5cf4c9bcdb7fbd38eda76b37e49438903/traffic_ops/traffic_ops_golang/routes.go#L113

The raw logger is then used everywhere, rather than the `log` package helper functions, which panics if `nil`. It's acceptable to use the raw loggers, but they must be checked for nil, if so.

Note this cannot be fixed by initializing nil loggers with `ioutil.Discard` or similar, as that has considerable performance degradation over `nil` loggers, and will impact performance-intensive apps like Traffic Monitor.

**Comment by mitchell852** [comment]
@rob05c - can you put a severity level label on this? trivial, minor, major, critical...

**Comment by mitchell852** [comment]
apparently this was fixed by a PR by @jrushford but i'm not sure which one. @rob05c do you want to verify that it is fixed / close this issue?

**Comment by rob05c** [comment]
@mitchell852 It is not fixed.

https://github.com/apache/trafficcontrol/search?q=%22log.Error.%22+filename%3A*.go&unscoped_q=%22log.Error.%22+filename%3A*.go

**Comment by DylanVolz** [comment]
Ahh I misunderstand the issue is all, I saw that where you referenced the routes.go file both were wrapped in a nil check now and thought that was all you were referring to.

**Comment by rob05c** [comment]
Ah, sorry. Yes, that was just one instance of the issue. We need to make sure all access to the raw logger objects checks for nil (or uses the access functions). Otherwise, the app will panic if someone tries to run it with all the loggers set to nil in the config (which is unusual in production, but perfectly reasonable for someone to do).

**Comment by shamrickus** [comment]
It looks like in the past few years these issues have been resolved. There are no raw accesses/usages of [Error](https://github.com/apache/trafficcontrol/search?p=1&q=%22log.Error.%22+filename%3A%2A.go&unscoped_q=%22log.Error.%22+filename%3A%2A.go)/[Event](https://github.com/apache/trafficcontrol/search?q=%22log.Event.%22+filename%3A*.go).
